# --- MySQL ---
mysql.datasource.jdbc-url=jdbc:mysql://icopoghru9oezxh8.cbetxkdyhwsb.us-east-1.rds.amazonaws.com:3306/vj405xbpvcud57ju
mysql.datasource.username=c650tzngv9hbki1r
mysql.datasource.password=a0j7fxgnki38y8b6
mysql.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
mysql.datasource.maximum-pool-size=10
mysql.datasource.minimum-idle=2
mysql.datasource.idle-timeout=30000
mysql.datasource.max-lifetime=1800000

# --- PostgreSQL ---
postgres.datasource.jdbc-url=jdbc:postgresql://dpg-d6cs0gbh46gs73co6tlg-a.frankfurt-postgres.render.com:5432/tournament_postgres
postgres.datasource.username=tournament_postgres_user
postgres.datasource.password=VStl6Ru4pXOkhT2Z3CRG5mT6Nyav2EgE
postgres.datasource.driver-class-name=org.postgresql.Driver
postgres.datasource.maximum-pool-size=10
postgres.datasource.minimum-idle=2
postgres.datasource.idle-timeout=30000
postgres.datasource.max-lifetime=1800000

spring.security.user.name=admin
spring.security.user.password=admin
spring.security.user.roles=ADMIN

jwt.secret=mysecretkey1234567890
jwt.expiration=3600000